# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed05b624fe279684c1796bc00d60a85078d4d680af56d75d9aa2b7ad1fdd3da0e008a7ef2c6b21f1509d8bc661b5a484de23982cfaf8ca62b0a7e0f3f09a71bc

test:
  secret_key_base: 79021913487059f79db2d39e14ed2ba135f8c51a963854360187a0bf84b1928628af8bf8c4317d24833557ed7d2da4cf0bcfccc38b98cb3e42297ab9b4a3eff8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
